base_images:
  ansible:
    name: "4.17"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.17"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.17"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.17"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-debug-vsphere
  cron: '@yearly'
  steps:
    cluster_profile: vsphere-connected-2
    env:
      SLEEP_DURATION: 10m
    leases:
    - env: VSPHERE_BASTION_LEASED_RESOURCE
      resource_type: vsphere-connected-2-quota-slice
    post:
    - ref: cucushift-installer-wait
    - chain: cucushift-installer-rehearse-vsphere-upi-disconnected-deprovision
    pre:
    - chain: cucushift-installer-rehearse-vsphere-upi-disconnected-secureboot-provision
- as: installer-rehearse-ibmcloud
  cron: '@yearly'
  steps:
    cluster_profile: ibmcloud-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-private-sshkey
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.17
